name: upper-build
on:
    push:
        paths:
            - '.github/workflows/upper-build.yml'
            - 'upper/**'
    workflow_dispatch: #manual

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: pwd && ls -al
            - uses: actions/checkout@v4
            - run: pwd && ls -al
            - run: go version
            - uses: actions/setup-go@v5
              with:
                  go-version: '1.22'
            - run: go version
            #new step named 'multi-line script' that runs a multi-line script
            - name: multi-line script
              run: |
                echo 'cd upper:'
                cd upper
                echo 'pwd:'
                pwd
                echo 'ls:'
                ls
                echo 'go build:'
                go build
                echo 'ls:'
                ls
                echo 'go test:'
                go test
                echo './upper foo the bar:'
                ./upper foo the bar