name: upper-build
on:
    push:
        paths:
            - '.github/workflows/upper-build.yml'
            - 'upper/**'
    workflow_dispatch: #manual

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: pwd && ls -al
            - uses: actions/checkout@v4
            - run: pwd && ls -al
            - run: go version
            - uses: actions/setup-go@v5
              with:
                  go-version: '1.22'
            - run: go version
            - name: Build Go app
              run: go build -o upper

            - name: Run tests
              run: go test

            - name: multi-line script
              run: |
                chmod +x upper
                echo "running upper..."
                ./upper foo the bar
